### ISSUE TITLE
去除水印的功能失效了，我发现水印没有被去除

### ISSUE THREAD

**Issue by zhangcunxiang** [YuJian920/nodeSpider_tiktok#1]
重现步骤：
我修改了要下载的抖音用户，type 改成 了 post，之后，npm install， npm run start
在post文件夹中，下载好的视频还是有抖音的水印

**Comment by zhangcunxiang** [comment]
<img width="405" alt="image" src="https://user-images.githubusercontent.com/5790065/234540047-14dc872d-466f-47a3-a130-ecf321938bc3.png">

**Comment by zhangcunxiang** [comment]
事实上，将 cnfig.ts 文件中的 HDDownloadUrl 常量中的 ”playwm“改成”play“ 再运行程序，就可以下载到无水印的视频了
希望对之后有需要的人有帮助

**Comment by YuJian920** [comment]
我测试了一下，还真是有水印的链接，现在已经提交修改了，感谢反馈
