### ISSUE TITLE
如何获得user和odin_tt, passport_csrf_token?

### ISSUE THREAD

**Issue by Hayast** [YuJian920/nodeSpider_tiktok#2]
"user": "https://v.douyin.com/ABYrVmt/",
  "type": "like",
  "limit": 100,
  "odin_tt": "324fb4ea4a89c0c05827e18a1ed9cf9bf8a17f7705fcc793fec935b637867e2a5a9b8168c885554d029919117a18ba69",
  "passport_csrf_token": "2f142a9bb5db1f81f249d6fc997fe4a1",

![image](https://user-images.githubusercontent.com/111619181/235304129-f9a44431-590c-43cc-95d4-8dc7b76d4591.png)

只有抖音号

**Comment by YuJian920** [comment]
如果脚本运行正常，odin_tt 和 passport_csrf_token 都不需要改，至于 user 直接复制用户主页的 url 就行了
