### ISSUE TITLE
只能下载第一页的视频

### ISSUE THREAD

**Issue by linsamasama** [YuJian920/nodeSpider_tiktok#6]

**Comment by YuJian920** [comment]
<img width="346" alt="20240519001302" src="https://github.com/YuJian920/nodeSpider_tiktok/assets/30545603/c5ab87b4-c098-42c9-9558-bd59aa120ddb">

我这里是没有问题的，检查一下 config.js 中的 odin_tt、passport_csrf_token、sessionid 填对了没

**Comment by linsamasama** [comment]
thanks 原来要配置，文档没写，还以为不需要，我这就去试试

**Comment by YuJian920** [comment]
> thanks 原来要配置，文档没写，还以为不需要，我这就去试试

晚点我把这几项必填的要求给加上
