### ISSUE TITLE
表哥我想问一下，获取完了怎么不下载啊

### ISSUE THREAD

**Issue by Philae994** [YuJian920/nodeSpider_tiktok#7]
开始处理第 1 个用户下载
开始获取 ===> 发布列表
获取内容 ===> 1 页
获取内容 ===> 2 页
获取内容 ===> 3 页
获取内容 ===> 4 页
获取内容 ===> 5 页
获取内容 ===> 6 页
获取内容 ===> 7 页
获取内容 ===> 8 页
获取内容 ===> 9 页
获取内容 ===> 10 页
获取内容 ===> 11 页
获取内容 ===> 12 页
获取内容 ===> 13 页
获取内容 ===> 14 页
获取内容 ===> 15 页
获取内容 ===> 16 页
获取内容 ===> 17 页
获取内容 ===> 18 页
获取内容 ===> 19 页
获取内容 ===> 20 页
内容获取完成 有效列表项 193 项

下载完成 任务结束 实际下载文件总数 ===> 0 / 193

**Comment by YuJian920** [comment]
这个问题有点尴尬，简单来讲解决办法就是 用低版本的 Node.js 版本，比如说 Node.js 16 来执行脚本。
或者你也可以用 tsc 编译之后，执行 js 产物。
