### ISSUE TITLE
node.js升级到23即可解决无法下载的问题

### ISSUE THREAD

**Issue by iamxiaobei** [YuJian920/nodeSpider_tiktok#9]

**Comment by YuJian920** [comment]
真的嘛？我晚点回去试一下

**Comment by YuJian920** [comment]
> 真的嘛？我晚点回去试一下

测试之后我这边是不行的，Node.js 23.5.0 在获取完列表之后直接退出，没有进行下载

**Comment by iamxiaobei** [comment]
我在mac下也是23.5.0，可以下载，可能我是把下载线程改为1了吧

**Comment by YuJian920** [comment]
> 我在mac下也是23.5.0，可以下载，可能我是把下载线程改为1了吧

可能是，无法下载的问题主要是因为多线程下的 Node.js 不认 .ts 结尾的文件，会直接抛出错误
